---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  # roles_path: "."
  hosts: all
  ansible_verbose: true
  ansible_version: latest
  require_chef_omnibus: false
  require_chef_for_busser: false
  additional_copy_path:
    - "."

platforms:
  - name: "ubuntu-14.04"
  - name: "centos-7.2"
  - name: "windows2012r2"
    driver:
      box: opentable/win-2012r2-standard-amd64-nocm
      ansible_connection: winrm
      ansible_platform: windows
      require_windows_support: true
      communicator: winrm
      provision: true
    transport:
      name: winrm
      winrm_transport: negotiate

suites:
  - name: default
    provisioner:
      playbook: role.yml

verifier: inspec
