---
- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: debian.yml
  when: ansible_os_family == "Debian"

- name: Install Opsview Agent
  package: name=opsview-agent
  when: ansible_os_family != "Windows"

- template:
    src: templates/nrpe.j2
    dest: "/opt/nrpe.cfg"
    owner: nagios
    group: nagios
    mode: 0644
  when: ansible_os_family != "Windows"

- include: Windows.yml
  when: ansible_os_family == "Windows"

- service: name=opsview-agent state=started
